name: LetheUI Build

on:
  workflow_dispatch:
  push:
    branches:
      - "1-lethe-pipeline-gui"

env:
  # Necessary for most environments as build failure can occur due to OOM issues
  NODE_OPTIONS: "--max-old-space-size=4096"

jobs:
  build:
    strategy:
      fail-fast: false
      matrix:
        build:
          - name: 'Lethe-UI'
            platform:  'linux/amd64'
            os: 'ubuntu-latest'
          - name: 'Lethe-UI'
            platform:  'windows/amd64'
            os: 'windows-latest'
          - name: 'Lethe-UI'
            platform:  'darwin/universal'
            os: 'macos-latest'

    runs-on: ${{ matrix.build.os }}
    steps:
      - name: Checkout
        uses: actions/checkout@v4
        with:
          submodules: recursive

      - name: Wails Build
        uses: dAppServer/wails-build-action@main
        id: build
        with:
          build-name: ${{ matrix.build.name }}
          build-platform: ${{ matrix.build.platform }}
          package: false
          wails-build-webview2: "embed"
          go-version: '1.25.4'
          app-working-directory: ${{ github.workspace }}/lethe_ui
          # Upload build assets
      - name: Upload upload-artifacts
        uses: actions/upload-artifact@v4
        with:
          name: Wails Build ${{runner.os}} ${{matrix.build.name}}
          files: |
            ${{github.workspace}}/lethe_ui/build/bin/*
